version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yaogc_dev
    ports:
      - "5432:5432"

